services:
  hs-vergleich-gui:       # Interner Service-Name ge√§ndert
    build: .
    container_name: hs-vergleich-gui  # Eindeutiger Container-Name zur Vermeidung von Konflikten
    ports:
      - "8080:80" 
